version: "2"

# Minimal linting for experimentation phase
# Only catch REAL BUGS, skip ALL style/optimization issues
# TODO: Re-enable strict linting before v1.0 release

linters:
  default: none
  enable:
    # Only real bugs - staticcheck with heavy exclusions
    - staticcheck

  settings:
    staticcheck:
      checks:
        - all
        # Disable ALL style/suggestion checks (SA = static analysis, ST = style, S = simple, QF = quick fix)
        - -ST*      # All style checks
        - -S1*      # All simplification suggestions
        - -QF*      # All quick fix suggestions
        - -SA1019   # Deprecation warnings
        - -SA4003   # Unsigned comparison
        - -SA4006   # Value never used
        - -SA4031   # Nil checks
        - -SA9003   # Empty branches

run:
  timeout: 5m
  build-tags:
    - integration
